### ISSUE TITLE
XML misspellings/typos in PDF (version 2.1.0)

### ISSUE THREAD

**Issue by peterdalle** [DILCISBoard/CITS-ERMS#30]
Here are some typos/misspellings of the XML I found when reading the PDF file (CITS ERMS version 2.1.0).

## Wrong casings/typos

- ERMS32: PDF says `@FileFormat` but XSD says `@fileFormat` 
- ERMS34: PDF says `@Path` but XSD says `@path`
- ERMS166: PDF says `@agenttype` but should be `@agentType` according to previous usage
- ERMS174: PDF is missing end quote for agentType: `record/agents/agent[@agentType=”main_signatory]/role`
- ERMS176: PDF has wrong casings in agentType: `record/agents/agent/@agenTtype=”other_signatory”`
- ERMS193: PDF says `record/IrunningNumber` bus XSD says `record/runningNumber`

## Missing elements

- ERMS55: PDF is missing the `restriction` element

## Mismatched elements

- ERMS157: Uses `record/notes/note` element for source but this element is already defined in ERMS150

Note: Haven't checked the `aggregation` element and its children since I didn't use that one.

**Comment by karinbredenberg** [comment]
Thank you for spotting this! Will be fixed in the new version.

**Comment by karinbredenberg** [comment]
Updates will be found in the PDF when version 2.2 is published.

**Comment by karinbredenberg** [comment]
**The suggestion is:**

***Updates in the PDF***
- ERMS32: PDF update to @FileFormat according to XSD @fileFormat
- ERMS34: PDF update to @Path according to XSD @path
- ERMS166: PDF update to @agenttype according to XSD @agentType
- ERMS174: PDF update with missing end quote for agentType: record/agents/agent[@agentType=”main_signatory]/role
- ERMS176: PDF update to correct casings in agentType: record/agents/agent/@agenTtype=”other_signatory”
- ERMS193: PDF update from record/IrunningNumber according to XSD record/runningNumber

***Missing element in PDF***
- ERMS55 update with the element name

***Question***
- ERMS157 is a repetition due to the same element being used for more than one purpose with the aid of the typing attribute 


**Board members acknowledgment of the issue:**
Tick the box in front of you name to indicate that you have looked at the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Voting**
(Decision making will be carried out on the basis of majority voting by all eligible members of the Board. In the case of a tied vote, decisions will be made at the discretion of the Chair)

Tick the box in front of you name to say yes to the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Comment by jmaferreira** [comment]
Hi,

O believe a closer inspection on typos is needed. After a quick glance at the document I found the following incongruences between the specification and the schema:

1. `addressline` vs `addressLine`
2. `contacLline` vs `contactLine`

My guess is that there are any others that need to be resolved before accepting this change. I would suggest that a complete enumeration of typos is prepared before acceptance.

**Comment by karinbredenberg** [comment]
Other typos fixed in this update in the textual document:
ERMS14, agencyCode
ERMS15, otherAgencyCode
ERMS16, otherAgencyCode
ERMS21, removal of double erms/control, fix of eventType
ERMS70, ippDuration
ERMS71, ippDuration
ERMS72, ippDuration
ERMS105, addressLine
ERMS106, addressLine
ERMS108, contactLine
ERMS115, disposalScheduled
ERMS132, physical_and_digital
ERMS148, extraId
ERMS191, directionDefinition and otherDirectionDefinition
ERMS249 correction of full element path
ERMS250 correction of full element path

**Comment by karinbredenberg** [comment]
6 DILCIS Board members have acknowledge the issue
5 DILCIS Board members agree with the solution

The update will be published 17th of May 2024.

**Comment by karinbredenberg** [comment]
Update have been published.
